-- Cria a tabela de clientes.
create table clientes (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    telefone varchar(20) not null,
    email varchar(120),
    cep varchar(9),
    logradouro varchar(120),
    bairro varchar(80),
    cidade varchar(80),
    uf varchar(2),
    profissional boolean not null
);

-- Cria a tabela de servicos oferecidos pelo salao.
create table servicos (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    preco_base decimal(10,2) not null,
    categoria varchar(60) not null
);

-- Cria a tabela de produtos vendidos pelo salao.
create table produtos (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    preco decimal(10,2) not null,
    estoque int not null,
    categoria varchar(60) not null
);

-- Cria a tabela de cursos para profissionais.
create table cursos (
    id bigint generated by default as identity primary key,
    titulo varchar(120) not null,
    preco decimal(10,2) not null,
    vagas int not null,
    nivel varchar(40) not null
);

-- Cria a tabela de agendamentos.
-- Ela se relaciona com clientes e servicos por meio de chaves estrangeiras.
create table agendamentos (
    id bigint generated by default as identity primary key,
    cliente_id bigint not null,
    servico_id bigint not null,
    data_hora timestamp not null,
    observacoes varchar(255),
    status varchar(30) not null,
    valor_cobrado decimal(10,2) not null,
    constraint fk_agendamento_cliente foreign key (cliente_id) references clientes(id),
    constraint fk_agendamento_servico foreign key (servico_id) references servicos(id)
);
